GET http://localhost/api/hotels

###
GET http://localhost/api/reviews?hotelId=1

###
GET http://localhost/api/average?hotelId=1

###
GET http://localhost/api/v2/hotel

###
GET http://localhost/api/v2/hotel/1/review

###
GET http://localhost/api/v2/hotel/2/average

###
GET http://localhost/api/v2/review

###
GET http://localhost/api/v2/chain

###
GET http://localhost/api/v2/chain/1/hotel

###
GET http://localhost/widget/6a2f41a3-c54c-fce8-32d2-0324e1c32e22.js

###